const getRefs = () => {
  return {
    addToWatchedBtn: document.querySelector('[data-add-to-watched]'),
    addToQueueBtn: document.querySelector('[data-add-to-queue]'),
    closeModalBtn: document.querySelector('[data-close-modal]'),
    closeTrailerBtn: document.querySelector('[data-close-trailer]'),
    errorWrap: document.querySelector('[data-error-wrap]'),
    homeBtn: document.querySelector('[data-home-btn]'),
    heroSlider: document.querySelector('[data-hero-slider]'),
    logo: document.querySelector('[data-logo]'),
    libSection: document.querySelector('[data-lib-section]'),
    libRoot: document.querySelector('[data-lib-root]'),
    libButtonsRoot: document.querySelector('[data-library-btns]'),
    libQueueBtn: document.querySelector('[data-lib-queue-btn]'),
    libWatchedBtn: document.querySelector('[data-lib-watched-btn]'),
    modalBackdrop: document.querySelector('[data-backdrop]'),
    modal: document.querySelector('[data-modal]'),
    modalContent: document.querySelector('[data-modal-content]'),
    modalMovie: document.querySelector('[data-modal-movie]'),
    modalQueueLabel: document.querySelector('[data-modal-queue-label]'),
    modalWatchedLabel: document.querySelector('[data-modal-watched-label]'),
    myLibBtn: document.querySelector('[data-my-lib-btn]'),
    paginationRoot: document.getElementById('tui-pagination-container'),
    popcornLoader: document.querySelector('[data-popcorn-loader]'),
    popularSection: document.querySelector('[data-popular-section]'),
    popularRoot: document.querySelector('[data-popular-root]'),
    searchSection: document.querySelector('[data-search-section]'),
    searchRoot: document.querySelector('[data-search-root]'),
    searchForm: document.querySelector('[data-form]'),
    sliderWrapper: document.querySelector('.swiper-wrapper'),
    trendingSection: document.querySelector('[data-trending-section]'),
    trailerRoot: document.querySelector('[data-trailer-root]'),
    trailerFrame: document.querySelector('[data-trailer-iframe]'),
    watchTrailerBtn: document.querySelector('[data-watch-trailer]'),
  };
};

export default getRefs;
